add_newline = false

[character]
success_symbol = "[➜](bold green)"

[gcloud]
disabled = true

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"
