add_newline = false

[character]
success_symbol = "[➜](bold green)"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[gcloud]
disabled = true

[package]
disabled = true

[java]
disabled = true

[scala]
disabled = true
