export SHELL=/usr/local/bin/zsh

export TRASHDIR=$HOME/Trash
export GIT=/usr/local/bin/git

export GOPATH=~/.go

#export _JAVA_OPTIONS=-Djava.awt.headless=true
export TMUX_DEFAULT_COMMAND="reattach-to-user-namespace -l zsh"
