export SHELL=/usr/local/bin/zsh

export TRASHDIR=$HOME/Trash

export GIT_AUTHOR_NAME="Andrey Kartashov"
export GIT_AUTHOR_EMAIL="akartashov@gilt.com"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export GIT=/usr/local/bin/git

export _JAVA_OPTIONS=-Djava.awt.headless=true
export TMUX_DEFAULT_COMMAND="reattach-to-user-namespace -l zsh"
