. $HOME/.dotfiles/zsh-common/zshrc

alias ls='gls --color'
alias ll='gls --color -lF'
alias st='git status'

E() { open -a /Applications/Emacs.app --args "$@" & disown }
e() { command emacsclient -nq "$@" }

export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
eval $(/usr/local/bin/gdircolors ~/.dircolors)
eval "$(jenv init -)"
