source $HOME/.dotfiles/zsh-common/zshrc
source /usr/local/share/zsh/site-functions/aws_zsh_completer.sh

alias ls='gls --color'
alias ll='gls --color -lF'
alias st='git status'

E() { open -a /Applications/Emacs.app --args "$@" & disown }
e() { command emacsclient -nq "$@" }

export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
eval $(/usr/local/bin/gdircolors ~/.dircolors)
#eval "$(jenv init -)"

# Launch GPG agent
gpgconf --launch gpg-agent

# GPG/SSH env
GPG_TTY=$(/usr/bin/tty)
SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
export GPG_TTY SSH_AUTH_SOCK

#. $HOME/.nix-profile/etc/profile.d/nix.sh
