. $HOME/.dotfiles/zsh-common/zshrc

alias ls='gls --color'
alias ll='gls --color -lF'
alias st='git status'

alias env-mobile='export AWS_PROFILE=aws-mobile'
alias env-pii='export AWS_PROFILE=hbc-pii'

E() { open -a /Applications/Emacs.app --args "$@" & disown }
e() { command emacsclient -nq "$@" }

export CLICOLOR=1
export LSCOLORS=dxfxcxdxbxegedabagacad
eval $(gdircolors ~/.dircolors)

