typeset -U path
path=(
  ~/sbin
  ~/bin
  ~/go/bin
  ~/.local/bin
  ~/.cargo/bin
  ~/.npm/node_modules/bin
  /sbin
  /bin
  /usr/sbin
  /usr/bin
  /usr/local/sbin
  /usr/local/bin
  /snap/bin

 $path[@]
)
