# .zshenv is sourced on all invocations of the shell, unless the -f option is
# set. It should contain commands to set the command search path, plus other
# important environment variables. `.zshenv' should not contain commands that
# produce output or assume the shell is attached to a tty.

# Skip these inside of nix shell
if [ -z "$IN_NIX_SHELL" ] ; then
  . /etc/environment

  if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ] ; then
  . $HOME/.nix-profile/etc/profile.d/nix.sh
  fi

  if [ -x /sbin/direnv ] ; then
    eval "$(direnv hook zsh)"
  fi
fi

typeset -U path

# Inherit PATH from nix when running inside nix shell
if [ -z "$IN_NIX_SHELL" ] ; then
  path=(
    ~/sbin
    ~/bin
    ~/.local/bin
    ~/.cargo/bin
    ~/.ghcup/bin
    ~/.config/emacs/bin
    ~/.local/share/coursier/bin
    /sbin
    /bin
    /usr/sbin
    /usr/bin
    /usr/local/sbin
    /usr/local/bin

  $path[@]
  )
else
  path=($(echo "$PATH" | sed -e 's/:/\n/g'))
fi

#POWERLINE_ZSH=/usr/lib/python3.9/site-packages/powerline/bindings/zsh/powerline.zsh
#if [ -e "$POWERLINE_ZSH" ] ; then
#  source "$POWERLINE_ZSH"
#fi

if [ -z "$TMPDIR" -a -e "/run/user/$(id -u)" ] ; then
  export TMPDIR="/run/user/$(id -u)"
fi

export EDITOR=vim
export SHELL=/usr/bin/zsh
export GIT=/usr/bin/git

export MEDIA_ROOT=/run/media/andrey/media

export JULIA_NUM_THREADS=6

#export QT_QPA_PLATFORM=wayland
#export QT_AUTO_SCREEN_SCALE_FACTOR=1

export NIX_BUILD_CORES=6

if [ -e $HOME/.zshenvlocal ] ; then
. $HOME/.zshenvlocal
fi

# apps linked against nix' glibc don't find locale definitions
# https://github.com/NixOS/nixpkgs/issues/38991
export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive

# https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth
export CLOUDSDK_PYTHON_SITEPACKAGES=1

# conflicts with espup?
#export IDF_PATH=$HOME/opt/esp-idf
#

if [ "$XDG_SESSION_TYPE" = "wayland" ] ; then
  export MOZ_ENABLE_WAYLAND=1
fi
