if [ -z "$TMPDIR" -a -e "/run/user/$(id -u)" ] ; then
  export TMPDIR="/run/user/$(id -u)"
fi

. $HOME/.dotfiles/zsh-linux/zprofile

export EDITOR=vim
export SHELL=/usr/bin/zsh
export GIT=/usr/bin/git

export MEDIA_ROOT=/run/media/andrey/media

#export QT_QPA_PLATFORM=wayland
#export QT_AUTO_SCREEN_SCALE_FACTOR=1
