# .zshenv is sourced on all invocations of the shell, unless the -f option is
# set. It should contain commands to set the command search path, plus other
# important environment variables. `.zshenv' should not contain commands that
# produce output or assume the shell is attached to a tty.


if [ -z "$TMPDIR" -a -e "/run/user/$(id -u)" ] ; then
  export TMPDIR="/run/user/$(id -u)"
fi

. $HOME/.dotfiles/zsh-linux/zprofile

export EDITOR=vim
export SHELL=/usr/bin/zsh
export GIT=/usr/bin/git

export MEDIA_ROOT=/run/media/andrey/media

export JULIA_NUM_THREADS=6

#export QT_QPA_PLATFORM=wayland
#export QT_AUTO_SCREEN_SCALE_FACTOR=1

export NIX_BUILD_CORES=6

export DOCKER_BUILDKIT=1

if [ -e $HOME/.zshenvlocal ] ; then
. $HOME/.zshenvlocal
fi

# apps linked against nix' glibc don't find locale definitions
# https://github.com/NixOS/nixpkgs/issues/38991
export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive

# https://cloud.google.com/iap/docs/using-tcp-forwarding#increasing_the_tcp_upload_bandwidth
export CLOUDSDK_PYTHON_SITEPACKAGES=1
