. $HOME/.dotfiles/zsh-common/zshrc
. $HOME/.nix-profile/etc/profile.d/nix.sh

if type kubectl > /dev/null ; then
  source <(kubectl completion zsh)
fi

E() { emacs "$@" & disown }
e() { emacsclient -nq "$@" }


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then

  export CLICOLOR=1
  export LSCOLORS=dxfxcxdxbxegedabagacad

  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

alias ls='ls --color=auto'
alias ll='ls -lF'
alias la='ls -A'

alias st='git status'

alias trm='trash-put'
alias open='xdg-open'


alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0| grep -E "state|to\ full|percentage"'

# Launch GPG agent
#gpgconf --launch gpg-agent

# GPG/SSH env
GPG_TTY=$(/usr/bin/tty)
SSH_AUTH_SOCK="/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"
export GPG_TTY SSH_AUTH_SOCK
